# This test runs 1 consumer on each of the specified hosts
# Should be run after producer test 
---
- name : Setup
  hosts: tools
  vars:
    bootstrap: 172.20.10.10:9092
    topicname_prefix: testtopic
    partitions: 128
    replicas: 3
    retention: 10800000 #3 hours
  tasks:
    - name: check testtopic
      shell: 
        cmd: >-
          kafka-topics --bootstrap-server {{bootstrap}} 
          --list --topic {{ topicname_prefix }}-{{ partitions }}
      register: topiclist
      tags:
        - test
    - debug:
        var: topiclist
    - name: create topic if it doesn't exist 
      shell:
        cmd: >-
          kafka-topics --bootstrap-server {{ bootstrap }}
          --topic {{ topicname_prefix }}-{{ partitions }}
          --create --partitions {{ partitions }}
          --replication-factor {{ replicas }}
          --config retention.ms={{ retention }}
          --config min.insync.replicas=2
      when: topiclist.stdout != "{{ topicname_prefix }}-{{ partitions }}"

- name: Tests
  strategy: free
  hosts:
    - tools
    - kafka_connect
  gather_facts: no
  vars:
    bootstrap: 172.20.10.10:9092
    topicname_prefix: testtopic
    partitions: 128
    throughput: -1
    record_size: 100
    num_records: 500000000
    acks: -1
  tasks:
    - name: consumer test
      command: >-
        kafka-consumer-perf-test
        --broker-list {{ bootstrap }}
        --group consumer-test
        --topic {{ topicname_prefix }}-{{ partitions }}
        --messages {{ num_records }}
        --show-detailed-stats
      register: consumer_sleeper
      async: 10800
      poll: 5
    - name: wait for consumers to end
      async_status:
        jid: "{{ consumer_sleeper.ansible_job_id }}"
      register: consumer_results
      until: consumer_results.finished
      retries: 30

    - debug: var=consumer_results.stdout

