# This test runs 1 producer on each of the specified hosts at max throughput
# Will write ~50GB per producer
---
- name : Setup
  hosts: tools
  vars:
    bootstrap: 172.20.10.10:9092
    topicname_prefix: testtopic
    partitions: 128
    replicas: 3
    retention: 10800000 #3 hours
  tasks:
    - name: check testtopic
      shell: 
        cmd: >-
          kafka-topics --bootstrap-server {{bootstrap}} 
          --list --topic {{ topicname_prefix }}-{{ partitions }}
      register: topiclist
      tags:
        - test
    - debug:
        var: topiclist
    - name: create topic if it doesn't exist 
      shell:
        cmd: >-
          kafka-topics --bootstrap-server {{ bootstrap }}
          --topic {{ topicname_prefix }}-{{ partitions }}
          --create --partitions {{ partitions }}
          --replication-factor {{ replicas }}
          --config retention.ms={{ retention }}
          --config min.insync.replicas=2
      when: topiclist.stdout != "{{ topicname_prefix }}-{{ partitions }}"

- name: Tests
  strategy: free
  hosts:
    - tools
    - kafka_connect
  gather_facts: no
  vars:
    bootstrap: 172.20.10.10:9092
    topicname_prefix: testtopic
    partitions: 128
    throughput: -1
    record_size: 100
    num_records: 50000000
    acks: -1
  tasks:
  - name: producer test
    command: >-
      kafka-producer-perf-test
      --topic {{ topicname_prefix }}-{{ partitions }}
      --producer-props bootstrap.servers={{ bootstrap }} acks={{ acks }}
      --record-size {{ record_size }}
      --throughput {{ throughput }}
      --num-records {{ num_records}}
    register: producer_sleeper
    async: 20800
    poll: 5
  - name: wait for producers to end
    async_status:
      jid: "{{ producer_sleeper.ansible_job_id }}"
    register: producer_results
    until: producer_results.finished
    retries: 30

  - debug: var=producer_results.stdout


